Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/trusty64"
  #config.vm.box_url = "http://vagrantcloud.com/ubuntu/boxes/trusty64"
  config.vm.synced_folder "./", "/mantra", id: "vagrant-root", create: true, group: "www-data", owner: "www-data"

  config.vm.provider "virtualbox" do |v|
    v.name = 'maelstrom'
  	v.cpus = 2
    v.memory = 2048
  end  

  config.vm.network :private_network, ip: "192.168.55.55"
  config.vm.provision :shell, :path => "provision.sh"

end
